# Generated by Django 4.1.3 on 2022-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
    ]
